### ISSUE TITLE
Readme Instructions unclear

### ISSUE THREAD

**Issue by ubuntupunk** [tinted-theming/base16-gtk-flatcolor#1]
Forgive me, I am a newbie when it comes to using flavours. You state:

> Now using your injector (if you don't have one, check out flavours), and configure it so the template will be built to both ~/.themes/FlatColor/colors3 and ~/.themes/FlatColors/colors2, using the subtemplates gtk-2 and gtk-3, respectively.

If I go to the flavours site, there is no gtk template and it isn't clear what is supposed to happen here. Could you perhaps be more instructive, or point me to an example?

**Comment by Misterio77** [comment]
Hey! Flavours config is basically one item per template/subtemplate you want to apply. If you want to theme both gtk3 and gtk2, you should make two entries on `~/.config/flavours/config.toml`. One for gtk-flatcolor gtk-2 and one for gtk-flatcolor gtk-3. Here's how the relevant part of my config file looks like:
```
[[item]]
file = '~/.themes/FlatColor/colors3'
template = 'gtk-flatcolor'
subtemplate = 'gtk-3'
rewrite = true
hook = 'systemctl restart --user xsettingsd'

[[item]]
file = '~/.themes/FlatColor/colors2'
template = 'gtk-flatcolor'
subtemplate = 'gtk-2'
rewrite = true
hook = 'gtkrc-reload'
```

**Comment by Misterio77** [comment]
Oh and i use a systemd unit file for xsettingsd as it is a daemon process (it keeps running till restarted). Here's my unit file (`~/.config/systemd/user/xsettingsd.service`):
```
[Unit]
Description="Xsettings Daemon"

[Service]
StartLimitBurst=20
StartLimitIntervalSec=5
Type=exec
WorkingDirectory=/home/misterio
ExecStart=/usr/bin/xsettingsd
Restart=no

[Install]
WantedBy=default.target
```

**Comment by Misterio77** [comment]
And here's the hooks i use, just in case you need them:
xsettingsd for reloading gtk3: https://github.com/derat/xsettingsd
gtkrc-reload for reloading gtk2: https://github.com/neeasade/gtkrc-reload

If you use Arch, xsettingsd is in the repositories, and gtkrc-reload is in the AUR

**Comment by Misterio77** [comment]
Let me know if you need any more help with it <3

**Comment by ubuntupunk** [comment]
Fantastic, thank you.
